# Generated by Django 3.2.4 on 2021-06-24 16:15

import annoying.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import images.models
import images.validators
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='mimetype',
            field=models.CharField(default='image/jpeg', max_length=20),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f6d8b5ec-576b-40e0-b4f2-cb400b934a47'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=images.models.upload_to, validators=[django.core.validators.validate_image_file_extension, django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='planthumbnailsetting',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_settings', to='images.plan'),
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(default=images.models.get_default_plan, on_delete=django.db.models.deletion.CASCADE, to='images.plan')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_tier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(validators=[images.validators.validate_duration_value])),
                ('identifier', models.CharField(max_length=10)),
                ('image', models.ForeignKey(db_column='imageproduct_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='image_expiring_token', to='images.imageproduct')),
            ],
        ),
    ]
