# Generated by Django 3.2.4 on 2021-06-25 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210624_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b7d2905a-79bd-41e2-a0b2-445d811192dd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
